"""empty message

Revision ID: 46659e75a008
Revises: 15791a4b1d49
Create Date: 2021-11-14 17:41:17.828533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46659e75a008'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=25), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('hair_color', sa.String(length=25), nullable=False),
    sa.Column('eye_color', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('climate', sa.String(length=25), nullable=False),
    sa.Column('terrain', sa.String(length=25), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=False),
    sa.Column('rotation_period', sa.Float(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character__fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_character'], ['character.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet__fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_table('planet__fav')
    op.drop_table('character__fav')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
